In [2]:
import os 
print(os.getcwd())

d:\GitHub\WormID\fDNC_Neuron_ID-master\wormnd\pkl_data_for_fDNC\benchmark_from_cell_detection

In [3]:


import pandas as pd

# # accs_full_fDNC = pd.read_csv('fDNC_pretrain_model___acc_top1_and_top5_combined.csv')
# # "D:\GitHub\WormID\fDNC_Neuron_ID-master\result\lab_split\fDNC_train_wo_SF__acc_top1_and_top5_and_cost lab_split.csv"
# # name = '/Users/lengyuner/Desktop/fDNC_Neuron_ID-master/result/lab_split/fDNC_train_wo_SF__acc_top1_and_top5_and_cost lab_split.csv'

# # fDNC_train_wo_HL__acc_top1_and_top5_and_cost lab_split.csv
# name = '/Users/lengyuner/Desktop/fDNC_Neuron_ID-master/result/lab_split/fDNC_all__acc_top1_and_top5_combined lab_split.csv'
# name = '../result/Tianxiao/fDNC_all__acc_top1_and_top5_combined from_cell_detection.csv'
name = os.path.join(os.getcwd(), 'result', 'fDNC_all__acc_top1_and_top5_combined from_cell_detection.csv')
accs_full_fDNC = pd.read_csv(name)

accs_full_fDNC['Filename_1'] = accs_full_fDNC['Filename']

FileNotFoundError: [Errno 2] No such file or directory: 'd:\\GitHub\\WormID\\fDNC_Neuron_ID-master\\wormnd\\pkl_data_for_fDNC\\benchmark_from_cell_detection\\result\\fDNC_all__acc_top1_and_top5_combined from_cell_detection.csv'

In [4]:
accs_full_fDNC['Filename'].tolist()

['7',
 '2022-12-21-06',
 '20230918-17-21-0',
 '2021-12-03-w00-NP1',
 '20230506-12-56-00',
 '20190928_08',
 '2',
 '2023-01-13-07',
 '20191104_10',
 '2023-01-23-15',
 '20190925_04',
 '2023-01-09-15',
 '2022-02-12-w01-NP1',
 '2023-01-10-07',
 '20230928-16-0-0',
 '20230510-15-49-47',
 '2022-06-14-07',
 '20230322-18-57-04',
 '20190928_05',
 '2023-01-18-01',
 '20190924_03',
 '20230322-21-41-10',
 '6',
 '20221106-21-00-09',
 '20230506-14-24-57',
 '3',
 '2023-01-16-22',
 '20191030_03',
 '2022-03-05-w00-NP1',
 '2022-07-15-12',
 '20190929_02',
 '2023-01-23-08',
 '20230904-15-09-05',
 '20191104_08',
 '2022-06-28-01',
 '20190924_02',
 '20221106-21-23-19',
 '2023-01-16-15',
 '2022-01-22-w04-NP1',
 '20230918-9-54-0',
 '20230322-20-16-50',
 '1',
 '20230510-13-25-46',
 '20190929_05',
 '20190929_03',
 '20231013-11-11-0',
 '2023-01-05-18',
 '20221215-20-02-49',
 '2023-01-09-22',
 '2022-02-12-w00-NP1',
 '2023-03-07-01',
 '20190928_13',
 '20230506-15-01-45',
 '2023-01-16-01',
 '8',
 '2022-04-26-w01-NP1',
 '20190924_01',
 '20231013-13-28-0',
 '4',
 '20230322-22-43-03',
 '2023-01-16-08',
 '20190929_07',
 '2023-01-17-07',
 '20190925_01',
 '20230928-11-14-0',
 '20221028-18-48-00',
 '2023-01-23-21',
 '20230909-16-48-09',
 '2022-02-22-w04-NP1',
 '20230918-13-21-0',
 '20190928_07',
 '20230510-12-53-34',
 '2022-04-26-w00-NP1',
 '9',
 '2022-07-20-01',
 '20190928_01',
 '5',
 '2023-01-06-08',
 '20221106-21-47-31',
 '20190929_06',
 '20230928-14-27-0',
 '20191030_07',
 '2023-01-17-01',
 '2023-01-19-08',
 '2022-06-14-01',
 '2022-02-11-w03-NP1',
 '2022-06-14-13',
 '20230506-15-33-51',
 '2022-04-01-w00-NP1',
 '20230904-15-59-40',
 '20190928_11',
 '2023-01-06-01',
 '20190928_03',
 '20230904-14-30-52']

In [5]:
accs_full_fDNC

,Filename,Best_template,top1,top2,top3,top4,top5,cost,task,Filename_1
0,7,8,0.335616,0.397260,0.438356,0.479452,0.506849,6.346388,train_0,7
1,2022-12-21-06,2022-07-26-01,0.182258,0.333871,0.348387,0.373387,0.391129,4.646568,train_0,2022-12-21-06
2,20230918-17-21-0,20230918-9-54-0,0.031509,0.051410,0.067993,0.084577,0.099502,5.787603,train_0,20230918-17-21-0
3,2021-12-03-w00-NP1,2022-02-12-w00-NP1,0.362416,0.530201,0.570470,0.604027,0.651007,6.251974,train_0,2021-12-03-w00-NP1
4,20230506-12-56-00,20230322-18-57-04,0.416446,0.527851,0.652520,0.801061,0.809019,5.882117,train_0,20230506-12-56-00
...,...,...,...,...,...,...,...,...,...,...
89,20230904-15-59-40,20230510-15-49-47,0.298368,0.463869,0.603730,0.671329,0.706294,7.047992,train_4,20230904-15-59-40
90,20190928_11,20190928_13,0.083333,0.154762,0.190476,0.238095,0.273810,5.999477,train_4,20190928_11
91,2023-01-06-01,2022-07-26-01,0.016624,0.026854,0.058824,0.094629,0.115090,4.495649,train_4,2023-01-06-01
92,20190928_03,20190929_02,0.030100,0.036789,0.063545,0.083612,0.093645,5.298217,train_4,20190928_03
93,20230904-14-30-52,20230322-18-57-04,0.464602,0.573009,0.630531,0.668142,0.672566,5.640999,train_4,20230904-14-30-52

In [6]:
# Skipping files that have obvious artifacts or known alignment issues
skipfiles = ['20231013-9-30-0', '20230412-20-15-17', '2023-01-23-01', '20239828-11-14-0', '2023-01-05-01', '2023-01-10-14', '2022-06-28-07', '2022-07-26-01', '2023-01-19-15', '2022-07-15-06', '2022-08-02-01', '2023-01-09-08', '2023-01-09-28', '2023-01-10-14', '2023-01-17-14', '2023-01-19-22', '2023-01-23-01', '7_YAaLR', '11_YAaLR', '20_YAaLR', '38_YAaDV', '55_YAaDV', '56_YAaDV', '62_YAaLR', '64_YAaDV', '70_YAaLR', '76_YAaDV']

In [7]:
accs_full_fDNC[accs_full_fDNC['Filename_1']=='38_YAaDV']

Empty DataFrame
Columns: [Filename, Best_template, top1, top2, top3, top4, top5, cost, task, Filename_1]
Index: []

In [8]:

name = "group_assigns.csv" 
group_assigns_df = pd.read_csv(name) 

# group_original = group_assigns_df[group_assigns_df['Group'] == 'original']['Filename'].tolist()
filenames = group_assigns_df['Filename'].tolist()
print(group_assigns_df.head())

   Unnamed: 0  Filename     Group Dataset  ID_skip
0           0  56_YAaDV  original   NP_og    False
1           1  38_YAaDV  original   NP_og    False
2           2  76_YAaDV  original   NP_og    False
3           3  11_YAaLR  original   NP_og    False
4           4  64_YAaDV  original   NP_og    False

In [9]:
print(set(group_assigns_df['Dataset']))

{'NP_og', 'SK1', 'SF', 'SK2', 'EY', 'KK', 'HL'}

In [10]:
# Merge the DataFrames on the 'Filename' column
merged_df = pd.merge(group_assigns_df, accs_full_fDNC, on='Filename', how='right')

# Display the merged DataFrame
print("\nMerged DataFrame:")
print(merged_df.head())
print(set(merged_df['Dataset']))

Merged DataFrame:
   Unnamed: 0            Filename Group Dataset  ID_skip       Best_template  \
0          15                   7     0      HL    False                   8
1          85       2022-12-21-06     0      SF    False       2022-07-26-01
2          71    20230918-17-21-0     0      KK    False     20230918-9-54-0
3          40  2021-12-03-w00-NP1     0     SK2    False  2022-02-12-w00-NP1
4          55   20230506-12-56-00     0     SK1    False   20230322-18-57-04

       top1      top2      top3      top4      top5      cost     task  \
0  0.335616  0.397260  0.438356  0.479452  0.506849  6.346388  train_0
1  0.182258  0.333871  0.348387  0.373387  0.391129  4.646568  train_0
2  0.031509  0.051410  0.067993  0.084577  0.099502  5.787603  train_0
3  0.362416  0.530201  0.570470  0.604027  0.651007  6.251974  train_0
4  0.416446  0.527851  0.652520  0.801061  0.809019  5.882117  train_0

           Filename_1
0                   7
1       2022-12-21-06
2    20230918-17-21-0
3  2021-12-03-w00-NP1
4   20230506-12-56-00
{'SK1', 'SF', 'SK2', 'EY', 'KK', 'HL'}

In [11]:
df_dataset = merged_df[~merged_df['Filename'].isin(skipfiles)]

In [12]:
low_labels = ['HL','SF','SK1','SK2']

high_labels = ['NP','EY','KK']

print(set(df_dataset['Dataset']))

import numpy as np
all_labels = low_labels+high_labels

{'SK1', 'SF', 'SK2', 'EY', 'KK', 'HL'}

In [ ]:
# Group by 'Dataset' and compute mean and std for 'acc_top1' and 'acc_top5'
group_stats = df_dataset[df_dataset['Dataset'].isin(all_labels)].groupby('Dataset').agg(
    acc_top1_mean=('top1', 'mean'),
    acc_top1_std=('top1', 'std'),
    acc_top5_mean=('top5', 'mean'),
    acc_top5_std=('top5', 'std')
).reset_index()
print(group_stats)

print(np.mean(group_stats['acc_top1_mean']),np.std(group_stats['acc_top1_mean']))
print(np.mean(group_stats['acc_top5_mean']),np.std(group_stats['acc_top5_mean']))

print('top1:',
    "{:.2}".format(np.mean(group_stats['acc_top1_mean'])), '±'
      "{:.2}".format(np.std(group_stats['acc_top1_mean'])))
print('top5:',
      "{:.2}".format(np.mean(group_stats['acc_top5_mean'])), '±'
      "{:.2}".format(np.std(group_stats['acc_top5_mean'])))

In [14]:
# Group by 'Dataset' and compute mean and std for 'acc_top1' and 'acc_top5'
group_stats = df_dataset[df_dataset['Dataset'].isin(all_labels)].groupby('Dataset').agg(
    acc_top1_mean=('top1', 'mean'),
    acc_top1_std=('top1', 'std'),
    acc_top5_mean=('top5', 'mean'),
    acc_top5_std=('top5', 'std')
).reset_index()
print(group_stats)

print(np.mean(group_stats['acc_top1_mean']),np.std(group_stats['acc_top1_mean']))
print(np.mean(group_stats['acc_top5_mean']),np.std(group_stats['acc_top5_mean']))

print('top1:',
    "{:.2}".format(np.mean(group_stats['acc_top1_mean'])), '±'
      "{:.2}".format(np.std(group_stats['acc_top1_mean'])))
print('top5:',
      "{:.2}".format(np.mean(group_stats['acc_top5_mean'])), '±'
      "{:.2}".format(np.std(group_stats['acc_top5_mean'])))

  Dataset  acc_top1_mean  acc_top1_std  acc_top5_mean  acc_top5_std
0      EY       0.043427      0.024865       0.167904      0.070240
1      HL       0.284071      0.109241       0.566758      0.147752
2      KK       0.026236      0.017083       0.114060      0.044221
3      SF       0.073725      0.062751       0.178937      0.113752
4     SK1       0.549417      0.165190       0.757149      0.124806
5     SK2       0.526637      0.091411       0.754144      0.088557
0.2505854134243304 0.22028519239738803
0.423158532229349 0.2775074017988984

top1: 0.25 ±0.22
top5: 0.42 ±0.28

{'SK2', 'KK', 'SK1', 'HL', 'EY', 'SF'}

In [19]:
# df_dataset

,Unnamed: 0,Filename,Group,Dataset,ID_skip,Best_template,top1,top2,top3,top4,top5,cost,Filename_1
0,16,6,1,HL,False,2,0.761062,0.761062,0.761062,0.761062,0.761062,4.432300,6
1,15,7,0,HL,False,9,0.931624,0.931624,0.931624,0.931624,0.931624,6.218977,7
2,85,2022-12-21-06,0,SF,False,2023-01-17-14,0.761194,0.761194,0.761194,0.761194,0.761194,6.094840,2022-12-21-06
3,56,20221106-21-00-09,1,SK1,False,20221215-20-02-49,0.862069,0.862069,0.862069,0.862069,0.862069,4.023531,20221106-21-00-09
4,57,20230322-20-16-50,2,SK1,False,20230322-21-41-10,0.715447,0.715447,0.715447,0.715447,0.715447,3.950113,20230322-20-16-50
...,...,...,...,...,...,...,...,...,...,...,...,...,...
98,65,20230322-21-41-10,0,SK1,False,20230322-20-16-50,0.783019,0.783019,0.783019,0.783019,0.783019,4.485289,20230322-21-41-10
99,31,20190924_01,2,EY,False,20190925_01,0.552486,0.552486,0.552486,0.552486,0.552486,6.012658,20190924_01
100,78,20231013-13-28-0,2,KK,False,20231013-11-11-0,0.376623,0.376623,0.376623,0.376623,0.376623,17.020940,20231013-13-28-0
102,46,2022-01-22-w04-NP1,1,SK2,False,2022-02-12-w01-NP1,0.764706,0.764706,0.764706,0.764706,0.764706,6.620923,2022-01-22-w04-NP1
103,77,20230918-9-54-0,1,KK,False,20230918-17-21-0,0.560000,0.560000,0.560000,0.560000,0.560000,17.312691,20230918-9-54-0

In [134]:

# print('Full CRFID average accuracy low labels:')
# print(np.mean(np.asarray(df_dataset[df_dataset['Dataset'].isin(low_labels)]['top1'])))
# print(np.mean(np.asarray(df_dataset[df_dataset['Dataset'].isin(low_labels)]['top5'])))
# # print(np.mean(np.asarray(df_dataset[(df_dataset['Atlas']=='Full')&(df_dataset['Model']=='CRFID')&(df_dataset['Rank']==5)&(df_dataset['Num_labeled']<neur_quartiles[2])]['top5'])))
# print('Full CRFID average accuracy high labels:')
# print(np.mean(np.asarray(df_dataset[df_dataset['Dataset'].isin(high_labels)]['top1'])))
# print(np.mean(np.asarray(df_dataset[df_dataset['Dataset'].isin(high_labels)]['top5'])))
# # print(np.mean(np.asarray(df_dataset[(df_dataset['Atlas']=='Full')&(df_dataset['Model']=='CRFID')&(df_dataset['Rank']==1)&(df_dataset['Num_labeled']>=neur_quartiles[2])]['Accuracy'])))
# # print(np.mean(np.asarray(df_dataset[(df_dataset['Atlas']=='Full')&(df_dataset['Model']=='CRFID')&(df_dataset['Rank']==5)&(df_dataset['Num_labeled']>=neur_quartiles[2])]['Accuracy'])))
# print('Full CRFID average accuracy:')
# print(np.mean(np.asarray(df_dataset[df_dataset['Dataset'].isin(all_labels)]['top1'])))
# print(np.mean(np.asarray(df_dataset[df_dataset['Dataset'].isin(all_labels)]['top5'])))

Full CRFID average accuracy low labels:
0.5239493634278402
0.732141192373792
Full CRFID average accuracy high labels:
0.2878479360398453
0.49678656775109753
Full CRFID average accuracy:
0.4511095613613311
0.6595317869050884

In [135]:
# # Group by 'Dataset' and compute mean and std for 'acc_top1' and 'acc_top5'
# group_stats = df_dataset[df_dataset['Dataset'].isin(low_labels)].groupby('Group').agg(
#     acc_top1_mean=('top1', 'mean'),
#     acc_top1_std=('top1', 'std'),
#     acc_top5_mean=('top5', 'mean'),
#     acc_top5_std=('top5', 'std')
# ).reset_index()
# print(group_stats)
# print(np.mean(group_stats['acc_top1_mean']))
# print(np.mean(group_stats['acc_top5_mean']))
# print(np.std(group_stats['acc_top1_mean']))
# print(np.std(group_stats['acc_top5_mean']))

  Group  acc_top1_mean  acc_top1_std  acc_top5_mean  acc_top5_std
0     0       0.564958      0.141644       0.741811      0.103353
1     1       0.532094      0.134155       0.765919      0.096575
2     2       0.554449      0.159267       0.751910      0.123786
3     3       0.481534      0.486947       0.659532      0.534813
4     4       0.479486      0.155900       0.735982      0.106267
0.5225042522801622
0.7310307468527155
0.03589958080654212
0.0371640874901724

In [136]:

# # Group by 'Dataset' and compute mean and std for 'acc_top1' and 'acc_top5'
# group_stats = df_dataset[df_dataset['Dataset'].isin(high_labels)].groupby('Group').agg(
#     acc_top1_mean=('top1', 'mean'),
#     acc_top1_std=('top1', 'std'),
#     acc_top5_mean=('top5', 'mean'),
#     acc_top5_std=('top5', 'std')
# ).reset_index()
# print(group_stats)
# print(np.mean(group_stats['acc_top1_mean']))
# print(np.mean(group_stats['acc_top5_mean']))
# print(np.std(group_stats['acc_top1_mean']))
# print(np.std(group_stats['acc_top5_mean']))

  Group  acc_top1_mean  acc_top1_std  acc_top5_mean  acc_top5_std
0     0       0.229600      0.190188       0.419921      0.231388
1     1       0.403841      0.155188       0.620781      0.090276
2     2       0.228892      0.149691       0.454746      0.175312
3     3       0.345591      0.149697       0.590968      0.127287
4     4       0.254857      0.219843       0.417835      0.276971
0.2925562902318777
0.5008501668304342
0.07019248347429828
0.08725966719750243

In [137]:

# # Group by 'Dataset' and compute mean and std for 'acc_top1' and 'acc_top5'
# group_stats = df_dataset[df_dataset['Dataset'].isin(all_labels)].groupby('Group').agg(
#     acc_top1_mean=('top1', 'mean'),
#     acc_top1_std=('top1', 'std'),
#     acc_top5_mean=('top5', 'mean'),
#     acc_top5_std=('top5', 'std')
# ).reset_index()
# print(group_stats)
# print(np.mean(group_stats['acc_top1_mean']))
# print(np.mean(group_stats['acc_top5_mean']))
# print(np.std(group_stats['acc_top1_mean']))
# print(np.std(group_stats['acc_top5_mean']))

  Group  acc_top1_mean  acc_top1_std  acc_top5_mean  acc_top5_std
0     0       0.458253      0.221969       0.639391      0.214399
1     1       0.496468      0.147868       0.725603      0.113911
2     2       0.445930      0.218956       0.652855      0.199329
3     3       0.436220      0.405424       0.636677      0.436974
4     4       0.417089      0.198108       0.647608      0.217995
0.45079207005642025
0.6604269241096403
0.02650991281756666
0.03309410795983355